#!/usr/bin/env node
/*
 * Build sitemap-images.xml: for every page in sitemap.xml, the content images
 * a reader sees on it (hero + images inside <main>), plus its og:image.
 * robots.txt declares the file next to sitemap.xml.
 *
 *   npm run sitemap:images
 *
 * What counts as a content image:
 *   - local files under /images/ that exist on disk
 *   - not the logo, not SVG icons, not /images/ads/ (Meta ad artwork)
 *   - not thumbnails inside links (related-post / blog-index cards): those are
 *     other pages' images and are listed on those pages instead
 * For responsive images the largest srcset candidate is used.
 *
 * Idempotent: the output is derived from sitemap.xml and the pages, so after a
 * merge that adds or removes pages just run it again (after sitemap.xml).
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const ORIGIN = 'https://www.be-tango.be';
const OUT = path.join(ROOT, 'sitemap-images.xml');

const locs = [...fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8').matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)]
  .map((m) => m[1]);

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}\\s*=\\s*"([^"]*)"`, 'i'));
  return m ? m[1] : null;
};

function largest(tag) {
  const srcset = attr(tag, 'srcset');
  if (srcset) {
    const best = srcset.split(',')
      .map((c) => c.trim().split(/\s+/))
      .filter((p) => p[0])
      .map(([url, d = '1w']) => ({ url, w: parseFloat(d) || 1 }))
      .sort((a, b) => b.w - a.w)[0];
    if (best) return best.url;
  }
  return attr(tag, 'src');
}

function keep(abs) {
  if (!abs || !abs.startsWith(ORIGIN + '/images/')) return false;
  const p = new URL(abs).pathname;
  if (/\/images\/ads\//.test(p)) return false;
  if (/logo/i.test(p) || /\.svg$/i.test(p) || /favicon|icon/i.test(p)) return false;
  return fs.existsSync(path.join(ROOT, decodeURIComponent(p)));
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

let total = 0;
const blocks = [];
for (const loc of locs) {
  const rel = decodeURIComponent(loc.slice(ORIGIN.length + 1));
  const file = path.join(ROOT, rel.endsWith('/') || rel === '' ? rel + 'index.html' : rel);
  if (!fs.existsSync(file)) { console.warn(`warning: no file for ${loc}`); continue; }
  const html = fs.readFileSync(file, 'utf8');

  const found = [];
  const add = (u) => {
    if (!u) return;
    let abs;
    try { abs = new URL(u.split('?')[0], loc).href; } catch { return; }
    if (keep(abs) && !found.includes(abs)) found.push(abs);
  };

  const og = html.match(/<meta[^>]*property="og:image"[^>]*>/i);
  const mainStart = html.search(/<main[\s>]/i);
  const mainEnd = html.search(/<\/main>/i);
  let body = mainStart >= 0 && mainEnd > mainStart ? html.slice(mainStart, mainEnd) : '';
  body = body.replace(/<a\b[^>]*>[\s\S]*?<\/a>/gi, ''); // drop linked cards
  for (const m of body.matchAll(/<img\b[^>]*>/gi)) add(largest(m[0]));
  if (og) add(attr(og[0], 'content'));

  if (!found.length) continue;
  total += found.length;
  blocks.push('  <url>\n    <loc>' + esc(loc) + '</loc>\n' +
    found.map((u) => '    <image:image>\n      <image:loc>' + esc(u) + '</image:loc>\n    </image:image>\n').join('') +
    '  </url>');
}

const xml = '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!-- Generated by _dev/scripts/sitemap-images.js (npm run sitemap:images). Do not edit by hand. -->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n' +
  '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n' +
  blocks.join('\n') + '\n</urlset>\n';
fs.writeFileSync(OUT, xml);
console.log(`sitemap-images.xml: ${blocks.length} pages, ${total} images`);
